FROM ubuntu

RUN apt-get update && \
    apt-get install -y

FROM gcc:latest

WORKDIR /hiperespectral

COPY master.cpp /hiperespectral
COPY jasperRidge2_R198/jasperRidge2_R198.hdr /hiperespectral/jasperRidge2_R198/jasperRidge2_R198.hdr
COPY include/stb_image_write.h /hiperespectral/include/stb_image_write.h

RUN g++ master.cpp -o master -I ./include

CMD ["./master"]