FROM ubuntu

RUN apt-get update && apg-get install -y \
build-essential 

FROM gcc:latest

WORKDIR /hiperespectral

COPY spectrum_replica.cpp /hiperespectral
COPY jasperRidge2_R198/jasperRidge2_R198.hdr /hiperespectral/jasperRidge2_R198/jasperRidge2_R198.hdr
COPY jasperRidge2_R198/jasperRidge2_R198.img /hiperespectral/jasperRidge2_R198/jasperRidge2_R198.img

RUN g++ spectrum_replica.cpp -o spec

CMD [ "./spec"]