FROM ubuntu

RUN apt-get update && apg-get install -y \
build-essential 

FROM gcc:latest

WORKDIR /hiperespectral

COPY spectrum_replica.cpp /hiperespectral
COPY jasperRidge2_R198 /hiperespectral/jasperRidge2_R198 
COPY run_replica.sh /hiperespectral

RUN g++ spectrum_replica.cpp -o spec

CMD ["source ./run_replica.sh"]