services:
  replica:
    image: hiperespectral-replica-swarm
    user: "1000:1000" 
    environment:
      TASK_ID: "{{.Task.Slot}}"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    volumes:
      - ./output:/hiperespectral/output
      - ./spectrums:/hiperespectral/spectrums

  master:
    image: hiperespectral-master
    user: "1000:1000"
    environment:
      NUM_FILES: 4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./output:/hiperespectral/output
    depends_on:
      - replica

#<user: "1000:1000"> this makes the host have the same permissions as docker so created directories/files can be removed easily without using chmod
#1000 is the id of the user and the group commonly in linux but it may be different onn each system