FROM ubuntu

RUN apt-get update && \
    apt-get install -y \
    g++ git wget cmake sudo

RUN apt-get install -y \
    build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
    python3-dev python3-numpy libtbbmalloc2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libdc1394-dev \
    libcanberra-gtk-module libcanberra-gtk3-module

RUN git clone https://github.com/opencv/opencv.git && \
    cd /opencv && mkdir build && cd build && \
    cmake -D CMAKE_BUILD_TYPE=Release -D    CMAKE_INSTALL_PREFIX=/usr/local .. && \
    make -j"$(nproc)" && \
    make install  && ldconfig

WORKDIR /hiperespectral

COPY master.cpp /hiperespectral/
COPY jasperRidge2_R198/jasperRidge2_R198.hdr /hiperespectral/jasperRidge2_R198/jasperRidge2_R198.hdr

RUN g++ master.cpp -o master `pkg-config opencv4 --cflags --libs`

CMD ["./master"]