version: '3.8'

services:
  spectrum:
    build:
      context: .
      dockerfile: Dockerfile_spectrum_replicas
    volumes:
      - ./output:/hiperespectral/output
      - ./spectrums:/hiperespectral/spectrums

  master:
    build:
      context: .
      dockerfile: Dockerfile_master
    volumes:
      - ./output:/hiperespectral/output

