FROM ubuntu

RUN apt-get update && apg-get install -y \
build-essential 

FROM gcc:latest

WORKDIR /hiperespectral

COPY spectrum_replica.cpp /hiperespectral
COPY jasperRidge2_R198 /hiperespectral/jasperRidge2_R198 
COPY get_host_number.sh /hiperespectral

RUN g++ spectrum_swarm.cpp -o spec
RUN source ./get_host_number.sh

CMD ["./spec"]