version: '3.8'

services:
  spectrum:
    build:
      context: .
      dockerfile: Dockerfile_spectrum
    volumes:
      - ./output:/hiperespectral/output

  master:
    build:
      context: .
      dockerfile: Dockerfile_master
    volumes:
      - ./output:/hiperespectral/output

