FROM ubuntu

RUN apt-get update && apg-get install -y \
build-essential 

FROM gcc:latest

WORKDIR /hiperespectral

COPY spectrum_replica.cpp /hiperespectral
COPY jasperRidge2_R198/jasperRidge2_R198.hdr /hiperespectral/jasperRidge2_R198/jasperRidge2_R198.hdr
COPY jasperRidge2_R198/jasperRidge2_R198.img /hiperespectral/jasperRidge2_R198/jasperRidge2_R198.img
COPY scripts/run_replica.sh /hiperespectral

RUN g++ spectrum_replica.cpp -o spec
RUN chmod 700 run_replica.sh

CMD [ "/bin/sh", "-c", "./run_replica.sh && ./spec"]