version: '3.8'

services:
  replica:
    env_file:
      - specs.env
    build:
      context: .
      dockerfile: Dockerfile_replicas
    volumes:
      - ./output:/hiperespectral/output
      - ./spectrums:/hiperespectral/spectrums

  master:
    env_file:
      - specs.env
    build:
      context: .
      dockerfile: Dockerfile_master
    volumes:
      - ./output:/hiperespectral/output