FROM ubuntu

RUN apt-get update && apg-get install -y \
build-essential 

FROM gcc:latest

WORKDIR /hiperespectral

COPY spectrum.cpp /hiperespectral
COPY ../jasperRidge2_R198 /hiperespectral/jasperRidge2_R198 

RUN g++ spectrum.cpp -o spec

CMD ["./spec"]